name: Build & Release ARM64 AppImage

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.2.3

env:
  FLUTTER_VERSION: 3.22.0
  TARGET_OS: linux # example `linux` , `windows` , `macos`
  ARCH: arm64 # example `arm64`

jobs:
  build-and-release-arm64:
    runs-on: ubuntu-22.04-arm

    permissions:
      contents: write  # Required to create/upload GitHub releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter ${{ env.FLUTTER_VERSION }}
        run: |
          git clone https://github.com/flutter/flutter.git --branch ${{ env.FLUTTER_VERSION }} --depth 1
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          export PATH="$PWD/flutter/bin:$PATH"
          flutter doctor -v
          flutter config --enable-${{ env.TARGET_OS }}-desktop
          flutter precache --${{ env.TARGET_OS }}

      - name: Run local build script
        run: chmod +x .github/scripts/build_and_package_${{ env.TARGET_OS }}_${{ env.ARCH }}.sh && .github/scripts/build_and_package_${{ env.ARCH }}.sh ${{ github.ref_name }}


      - name: Upload AppImage to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ github.ref_name }}"
          name: "${{ github.ref_name }}"
          body: "Automated release for ${{ github.ref_name }}"
          files: "artifacts/PactusGUI-${{ github.ref_name }}-${{ env.TARGET_OS }}-${{ env.ARCH }}.AppImage"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate release download links
        run: |
          TAG=${{ github.ref_name }}
          FILE=pactus_gui-aarch64.AppImage
          DOWNLOAD_URL="https://github.com/${{ github.repository }}/releases/download/${TAG}/${FILE}"
          RELEASE_URL="https://github.com/${{ github.repository }}/releases/tag/${TAG}"
          echo "Download URL: $DOWNLOAD_URL"
          echo "Release URL: $RELEASE_URL"
