name: Build & Release ARM64 AppImage

on:
  push:
    tags:
      - 'v*'  # Trigger on tags starting with v, e.g. v1.2.3

permissions:
  contents: write  # Required for creating or updating releases

jobs:
  build-arm:
    runs-on: ubuntu-22.04-arm  # native ARM64 hosted runner

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Flutter 3.22.0 from source
        run: |
          git clone https://github.com/flutter/flutter.git --branch 3.22.0 --depth 1
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          export PATH="$PWD/flutter/bin:$PATH"
          flutter doctor -v
          flutter config --enable-linux-desktop
          flutter precache --linux

      - name: Install dependencies & build Flutter Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libfuse2 cmake ninja-build wget appstream

      - name: Build Flutter Linux ARM64 App
        run: |
          flutter pub get
          flutter build linux --release --target-platform=linux-arm64

      - name: Package AppImage
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-aarch64.AppImage
          chmod +x appimagetool-aarch64.AppImage
          APPDIR=build/linux/arm64/release/bundle
          cp linux/pactus_gui.desktop $APPDIR/
          cp linux/pactus_gui.png $APPDIR/
          ./appimagetool-aarch64.AppImage "$APPDIR" pactus_gui-aarch64.AppImage
          mkdir -p artifacts
          mv pactus_gui-aarch64.AppImage artifacts/

      - name: Create or update GitHub release and upload AppImage
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: "Automated release for ${{ github.ref_name }}"
          files: artifacts/pactus_gui-aarch64.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate release download links
        run: |
          TAG=${{ github.ref_name }}
          FILE=pactus_gui-aarch64.AppImage
          DOWNLOAD_URL="https://github.com/${{ github.repository }}/releases/download/${TAG}/${FILE}"
          RELEASE_URL="https://github.com/${{ github.repository }}/releases/tag/${TAG}"
          echo "Download URL: $DOWNLOAD_URL"
          echo "Release URL: $RELEASE_URL"
